TwitterStatist/TwitterStatist/TwitterStatist/Controllers/SearcherController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TwitterStatist.Models;
using TwitterStatist.Repositores;
using Microsoft.AspNet.Identity;
using TwitterStatist.Helpers;
using PagedList;
using TwitterStatist.TweetManagement;

namespace TwitterStatist.Controllers
{
    

    public class SearcherController : Controller
    {
        private int randomCount = 15;
        public UserRepository _userRepo;
        private UserRepository userRepo
        {
            get
            {
                if (_userRepo == null)
                    _userRepo = new UserRepository();
                return _userRepo;
            }
            set
            {
                _userRepo = value;
            }
        }
        private SearcherRepository _searcherRepo;
        public SearcherRepository searcherRepo
        {
            get
            {
                if (_searcherRepo == null)
                    _searcherRepo = new SearcherRepository();
                return _searcherRepo;
            }
            set
            {
                _searcherRepo = value as SearcherRepository;
            }
        }
        private TwitterStatistContext db = new TwitterStatistContext();

        // GET: Searcher
        [Authorize]
        public async Task<ActionResult> Index()
        {
            User.Identity.GetUserId();
            //var searchers = db.Searchers.Include(s => s.ApplicationUser);
            ViewBag.Description = " Lista przedstawia searchery utworzone przez Ciebie.";

            return View(searcherRepo.GetAllSearchVMByUser(User.Identity.GetUserId()));
        }
        [Authorize(Roles ="Admin")]
        public async Task<ActionResult> SearcherForUser(string id)
        {
            return View("Index",searcherRepo.GetAllSearchVMByUser(id));
        }


        /// <summary>
        /// Metoda zwraca losową liczbę searcherów
        /// </summary>
        /// <returns></returns>
        public ActionResult RandomSearchers()
        {
            ViewBag.Title = "Losowe wyniki";
            ViewBag.Discribe = "Lista przedstawia losowo wybrane wyniki wyszukiwań.";

          return View("Index",searcherRepo.GetRandomSearchVM(randomCount));
        }


        public ViewResult TweetList(int? id,string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var tweets = searcherRepo.GetTweetBySearcherID(id.Value);
            if (!String.IsNullOrEmpty(searchString))
            {
                tweets = tweets.Where(s => s.Text.Contains(searchString)
                                       || s.Author.Contains(searchString)).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    tweets = tweets.OrderByDescending(s => s.Author).ToList();
                    break;
                case "Date":
                    tweets = tweets.OrderBy(s => s.Date).ToList(); ;
                    break;
                case "date_desc":
                    tweets = tweets.OrderByDescending(s => s.Date).ToList(); 
                    break;
                default:  // Name ascending 
                    tweets = tweets.OrderBy(s => s.Date).ToList(); 
                    break;
            }

            int pageSize = 30;
            int pageNumber = (page ?? 1);

           return View(tweets.ToPagedList(pageNumber, pageSize));
        }
                    
        // GET: Searcher/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var searcher = searcherRepo.GetSearcherVModel(id);
            if (searcher == null)
            {
                return HttpNotFound();
            }
            var userId = User.Identity.GetUserId();
            ViewBag.IsAuthor = (userId != null)? searcher.IdUser == userId : false;
            return View(searcher);
        }



        // GET: Searcher/Create
        [HttpGet]
        public ActionResult Create()
        {
                  return View();
        }

        private ulong GetUnixDateTime(DateTime date)
        {
            DateTime unixStart = DateTime.SpecifyKind(new DateTime(1970, 1, 1), DateTimeKind.Utc);
            return (ulong)Math.Floor((date.ToUniversalTime() - unixStart).TotalMilliseconds);
        }
        public JsonResult GetStatistic(int searcherId)
        {

            var TweetList = searcherRepo.GetTweetBySearcherID(searcherId);
            //var query = TweetList.AsEnumerable()
            //    .GroupBy(row => new
            //    {
            //        Date = row.Date.Date,
            //        Hour = row.Date.Date.Hour
            //    })
            //    .Select(grp => new
            //    {
            //        Date = grp.Key.Date,
            //        Hour = grp.Key.Hour,
            //        Count = grp.Count()
            //    });


            var hourGroups = TweetList.AsEnumerable()
    .Select(row => new { DateAndTime = row.Date, Row = row })
    .GroupBy(x => new { DateT = x.DateAndTime.Date, Hour = x.DateAndTime.Date.Hour });

            List<Stat> lstStat = new List<Stat>();

            foreach (var x in hourGroups)
            {

                var Day = x.GroupBy(d => new { Hour = d.DateAndTime.Hour });

                for (int i = 0; i < 24; i++)
                {
                    var HourDay = Day.Where(dh => dh.Key.Hour == i).FirstOrDefault();
                    if (HourDay != null)
                    {
                        lstStat.Add(new Stat(
                            GetUnixDateTime(x.Key.DateT.Date.AddHours(HourDay.Key.Hour)),
                            HourDay.Count()
                            ));
                    }
                    else
                    {
                        lstStat.Add(new Stat(
                                        GetUnixDateTime(x.Key.DateT.Date.AddHours(i)),
                                        0
                                     ));
                    }

                }
            }

                var rt = lstStat.Count();
            lstStat = lstStat.OrderBy(x => x.Date).ToList();

            var t = Json(lstStat, JsonRequestBehavior.AllowGet);
                return t;


            }

        public ActionResult Maps()
        {
            return View();
        }
        // POST: Searcher/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]


        public async Task<ActionResult> Create([Bind(Include = "Name,Query,Start, Latitude,Longitude,Distance, LocationValue")] SearcherViewModel searcher) //
        {
            if (ModelState.IsValid)
            {
                CheckLocation(ref searcher);
                searcherRepo.AddSearcherMVToUser(searcher, User.Identity.GetUserId());
                return RedirectToAction("Index");
            }
            return View(searcher);
        }


        // GET: Searcher/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Searcher searcher = await db.Searchers.FindAsync(id);
            if (searcher == null)
            {
                return HttpNotFound();
            }
            return View(searcher);
        }

        // POST: Searcher/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,IdUser,Name,IdWorkMode,Query,IdQueryMode,IdLand,Start,Precision")] Searcher searcher)
        {
            if (ModelState.IsValid)
            {
                db.Entry(searcher).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            //    ViewBag.IdUser = new SelectList(db.ApplicationUsers, "Id", "Email", searcher.IdUser);
            return View(searcher);
        }

        // GET: Searcher/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Searcher searcher = await db.Searchers.FindAsync(id);
            if (searcher == null)
            {
                return HttpNotFound();
            }
            return View(searcher);
        }

        //Get Searcher/ChangeWorkMode 
        public async Task<ActionResult> ChangeWorkMode(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Searcher searcher = await db.Searchers.FindAsync(id);
            if (searcher == null)
            {
                return HttpNotFound();
            }
            return View(searcher);
        }

        private void CheckLocation(ref SearcherViewModel searcher)
        {

TwitterStatist/TwitterStatist/TwitterStatist/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Tweet Statist</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        .admin
        {
           color: dodgerblue;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <img class="navbar-brand" src="~/Image/LogoSmall.png" width="70" alt="logo">
                @Html.ActionLink("Twit Statist", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dokumentacja", "About", "Home")</li>
                    <li>@Html.ActionLink("Losowe wyniki", "RandomSearchers", "Searcher")</li>
                  
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Searchers", "Index", "Searcher")</li>
                        //   if (@ViewBag.IsAdmin)
                        if (User.IsInRole("Admin"))
                        {
                            @*<li>@Html.ActionLink("Searcher Settings", "Index", "SearchSettings", null, new {  @class = "admin"}) </li>
                            <li> @Html.ActionLink("Query Settings", "Index", "QueryModes",null, new { @class = "admin" }) </li>*@
                            <li> @Html.ActionLink("Lista użytkowników", "UserList", "Account",null, new { @class = "admin" }) </li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Twit Statist</p>
        </footer>
    </div>


</body>
</html>

TwitterStatist/TwitterStatist/TwitterStatist/Views/Shared/_LocationPartial.cshtml
@*<script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>*@
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?v=3.26&key=AIzaSyAxqru5oB7vrLV0u1W_C8SObO0TUHi1Duc&sensor=false"></script>

<script src="~/Scripts/utility.js" type="text/javascript"></script>

<style>
    #map_canvas img {
        max-width: none;
    }
</style>

<!-- This css is to give a nice big popup "info window" when a marker is clicked on the map -->
<style>
    .infoDiv {
        height: 200px;
        width: 300px;
        -webkit-user-select: none;
        background-color: white;
    }
</style>
<br />
<!-- This is the div that will contain the Google Map -->
<div id="map_canvas" style="height: 550px;"></div>
<div id="divInfo" style="font-family: Arial; font-size: 12px; color: Red;">
</div>
<script type="text/javascript">
        var map;
        function LoadMap() {
            var center_pt = new google.maps.LatLng(28.992226, 77.705557);
            var mapOptions = {
                zoom: 4,
                center: center_pt,
                mapTypeControl: false,
                streetViewControl: true,
                zoomControlOptions: {
                    style: google.maps.ZoomControlStyle.SMALL
                }
            };

            map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
            map.setMapTypeId(google.maps.MapTypeId.ROADMAP);
            var styles = [
                                                                   { elementType: "geometry",
                                                                       stylers: [
                                                                               { hue: "#00ffe6" },
                                                                               { saturation: -10 }

                                                                       ]
                                                                   }, {
                                                                       featureType: "road",
                                                                       elementType: "geometry",
                                                                       stylers: [
                                                                               { lightness: 100 },
                                                                               { visibility: "simplified" }
                                                                       ]
                                                                   }, {
                                                                       featureType: "road",
                                                                       elementType: "labels",
                                                                       stylers: [
                                                                               { visibility: "off" }
                                                                       ]
                                                                   }
            ];

            map.setOptions({ styles: styles });
            initWidget(map);
        }
</script>
<!-- Enclose the Javascript in a "section" so that it is rendered in the correct order after scripts have been loaded etc -->
@section scripts {
    <section class="scripts">

        <script type="text/javascript">
                 $(document).ready(function () {
        //Initialize();
               LoadMap();
    });

    // Where all the fun happens
        </script>
    </section>
}